package com.shinowit.dao.mapper;

import com.shinowit.entity.City;
import com.shinowit.entity.CityCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Jan 12 22:38:14 CST 2015
     */
    int countByExample(CityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Jan 12 22:38:14 CST 2015
     */
    int deleteByExample(CityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Jan 12 22:38:14 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Jan 12 22:38:14 CST 2015
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Jan 12 22:38:14 CST 2015
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Jan 12 22:38:14 CST 2015
     */
    List<City> selectByExample(CityCriteria example);
    List<City> selectbypid(String provinceid);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Jan 12 22:38:14 CST 2015
     */
    City selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Jan 12 22:38:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") City record, @Param("example") CityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Jan 12 22:38:14 CST 2015
     */
    int updateByExample(@Param("record") City record, @Param("example") CityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Jan 12 22:38:14 CST 2015
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon Jan 12 22:38:14 CST 2015
     */
    int updateByPrimaryKey(City record);
}