package com.shinowit.dao.mapper;

import com.shinowit.entity.District;
import com.shinowit.entity.DistrictCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Mon Jan 12 22:36:33 CST 2015
     */
    int countByExample(DistrictCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Mon Jan 12 22:36:33 CST 2015
     */
    int deleteByExample(DistrictCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Mon Jan 12 22:36:33 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Mon Jan 12 22:36:33 CST 2015
     */
    int insert(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Mon Jan 12 22:36:33 CST 2015
     */
    int insertSelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Mon Jan 12 22:36:33 CST 2015
     */
    List<District> selectByExample(DistrictCriteria example);
    List<District> selectbycid(String cityid);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Mon Jan 12 22:36:33 CST 2015
     */
    District selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Mon Jan 12 22:36:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") District record, @Param("example") DistrictCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Mon Jan 12 22:36:33 CST 2015
     */
    int updateByExample(@Param("record") District record, @Param("example") DistrictCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Mon Jan 12 22:36:33 CST 2015
     */
    int updateByPrimaryKeySelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Mon Jan 12 22:36:33 CST 2015
     */
    int updateByPrimaryKey(District record);
}