package com.shinowit.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Gouwuche1 implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gouwuche1.MerchandiseID
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    private String merchandiseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gouwuche1.UserName
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gouwuche1.MerchandiseName
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    private String merchandisename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gouwuche1.Price
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gouwuche1.num
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gouwuche1.PicPath
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    private String picpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gouwuche1.totalmoney
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    private BigDecimal totalmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gouwuche1
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gouwuche1.MerchandiseID
     *
     * @return the value of gouwuche1.MerchandiseID
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public String getMerchandiseid() {
        return merchandiseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gouwuche1.MerchandiseID
     *
     * @param merchandiseid the value for gouwuche1.MerchandiseID
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public void setMerchandiseid(String merchandiseid) {
        this.merchandiseid = merchandiseid == null ? null : merchandiseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gouwuche1.UserName
     *
     * @return the value of gouwuche1.UserName
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gouwuche1.UserName
     *
     * @param username the value for gouwuche1.UserName
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gouwuche1.MerchandiseName
     *
     * @return the value of gouwuche1.MerchandiseName
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public String getMerchandisename() {
        return merchandisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gouwuche1.MerchandiseName
     *
     * @param merchandisename the value for gouwuche1.MerchandiseName
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public void setMerchandisename(String merchandisename) {
        this.merchandisename = merchandisename == null ? null : merchandisename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gouwuche1.Price
     *
     * @return the value of gouwuche1.Price
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gouwuche1.Price
     *
     * @param price the value for gouwuche1.Price
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gouwuche1.num
     *
     * @return the value of gouwuche1.num
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gouwuche1.num
     *
     * @param num the value for gouwuche1.num
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gouwuche1.PicPath
     *
     * @return the value of gouwuche1.PicPath
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gouwuche1.PicPath
     *
     * @param picpath the value for gouwuche1.PicPath
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath == null ? null : picpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gouwuche1.totalmoney
     *
     * @return the value of gouwuche1.totalmoney
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public BigDecimal getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gouwuche1.totalmoney
     *
     * @param totalmoney the value for gouwuche1.totalmoney
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    public void setTotalmoney(BigDecimal totalmoney) {
        this.totalmoney = totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gouwuche1
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Gouwuche1 other = (Gouwuche1) that;
        return (this.getMerchandiseid() == null ? other.getMerchandiseid() == null : this.getMerchandiseid().equals(other.getMerchandiseid()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getMerchandisename() == null ? other.getMerchandisename() == null : this.getMerchandisename().equals(other.getMerchandisename()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()))
            && (this.getPicpath() == null ? other.getPicpath() == null : this.getPicpath().equals(other.getPicpath()))
            && (this.getTotalmoney() == null ? other.getTotalmoney() == null : this.getTotalmoney().equals(other.getTotalmoney()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gouwuche1
     *
     * @mbggenerated Wed Jan 07 16:45:07 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMerchandiseid() == null) ? 0 : getMerchandiseid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getMerchandisename() == null) ? 0 : getMerchandisename().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        result = prime * result + ((getPicpath() == null) ? 0 : getPicpath().hashCode());
        result = prime * result + ((getTotalmoney() == null) ? 0 : getTotalmoney().hashCode());
        return result;
    }
}